package DB;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playlistDaoConfig;
    private final DaoConfig favoriteDaoConfig;

    private final PlaylistDao playlistDao;
    private final FavoriteDao favoriteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playlistDaoConfig = daoConfigMap.get(PlaylistDao.class).clone();
        playlistDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        playlistDao = new PlaylistDao(playlistDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);

        registerDao(Playlist.class, playlistDao);
        registerDao(Favorite.class, favoriteDao);
    }
    
    public void clear() {
        playlistDaoConfig.getIdentityScope().clear();
        favoriteDaoConfig.getIdentityScope().clear();
    }

    public PlaylistDao getPlaylistDao() {
        return playlistDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

}
