package DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE.
 */
public class Favorite {

    /** Not-null value. */
    private String VideoId;
    /** Not-null value. */
    private String VideoTitle;
    private String VideoDuration;
    private String VideoViewer;
    private String VideoUploadDate;
    private String VideoAuthor;
    private String VideoThumbnail;

    public Favorite() {
    }

    public Favorite(String VideoId) {
        this.VideoId = VideoId;
    }

    public Favorite(String VideoId, String VideoTitle, String VideoDuration, String VideoViewer, String VideoUploadDate, String VideoAuthor, String VideoThumbnail) {
        this.VideoId = VideoId;
        this.VideoTitle = VideoTitle;
        this.VideoDuration = VideoDuration;
        this.VideoViewer = VideoViewer;
        this.VideoUploadDate = VideoUploadDate;
        this.VideoAuthor = VideoAuthor;
        this.VideoThumbnail = VideoThumbnail;
    }

    /** Not-null value. */
    public String getVideoId() {
        return VideoId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoId(String VideoId) {
        this.VideoId = VideoId;
    }

    /** Not-null value. */
    public String getVideoTitle() {
        return VideoTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoTitle(String VideoTitle) {
        this.VideoTitle = VideoTitle;
    }

    public String getVideoDuration() {
        return VideoDuration;
    }

    public void setVideoDuration(String VideoDuration) {
        this.VideoDuration = VideoDuration;
    }

    public String getVideoViewer() {
        return VideoViewer;
    }

    public void setVideoViewer(String VideoViewer) {
        this.VideoViewer = VideoViewer;
    }

    public String getVideoUploadDate() {
        return VideoUploadDate;
    }

    public void setVideoUploadDate(String VideoUploadDate) {
        this.VideoUploadDate = VideoUploadDate;
    }

    public String getVideoAuthor() {
        return VideoAuthor;
    }

    public void setVideoAuthor(String VideoAuthor) {
        this.VideoAuthor = VideoAuthor;
    }

    public String getVideoThumbnail() {
        return VideoThumbnail;
    }

    public void setVideoThumbnail(String VideoThumbnail) {
        this.VideoThumbnail = VideoThumbnail;
    }

}
